"""Placeholder for sandboxed execution of LLM-generated visualization code.

In production this module would use a secure sandbox (e.g. Docker containers,
nsjail, or a WebAssembly runtime) to execute arbitrary Python code generated by
an LLM.  For now it exposes a thin stub that simply returns the output path so
the rest of the pipeline can be developed against a stable interface.
"""

import os
import uuid

from shared.config import get_settings
from shared.logger import get_logger

logger = get_logger(__name__)
settings = get_settings()


def execute_viz_code(code: str) -> str:
    """Execute Python visualization code and return the path to the output file.

    Args:
        code: A string containing Python code that generates a visualization.
              The code is expected to save an image to a path provided via
              the ``OUTPUT_PATH`` variable injected into its namespace.

    Returns:
        The filesystem path where the generated image was saved.

    .. warning::
        This implementation is **NOT sandboxed**.  In a production deployment
        the code would be executed inside an isolated environment with
        restricted file-system access, network policies, and resource limits.
    """
    # TODO: Replace with sandboxed execution (Docker / nsjail / Pyodide)
    viz_id = str(uuid.uuid4())
    output_path = os.path.join(settings.VIZ_OUTPUT_DIR, f"{viz_id}.png")

    logger.warning(
        "code_executor.execute_viz_code called -- sandboxing is NOT implemented. "
        "Skipping execution for safety."
    )

    # In production the code would be executed here, e.g.:
    #   sandbox.run(code, env={"OUTPUT_PATH": output_path}, timeout=30)
    #
    # For now we simply return the expected path without executing anything.
    return output_path
